name: release

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r test-requirements.txt
      - name: pytest
        run: pytest
      - name: tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: update version file
        run: |
          echo "${{ steps.tag_version.outputs.new_tag }}" > VERSION.txt

          git add -A
          git commit -m "tag as version ${{ steps.tag_version.outputs.new_tag }}"
          git push
      
      


