name: release

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r local_requirements.txt
      - name: pytest
        run: pytest
      - name: tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
